title: E-hääletuse vaatlejad
description: Elektroonse hääletuse siseriiklikud vaatlejad koondusid, et teha oma ametiuhkusest lähtuvalt oluline avaldus
theme: just-the-docs

url: https://vaatlejad.github.io

aux_links:
  Template Repository: https://github.com/vaatlejad/vaatlejad.github.io
